# Generated by Django 2.0.2 on 2018-03-15 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('male', models.BooleanField(default=True, verbose_name='男?')),
                ('phone', models.CharField(blank=True, default=0, max_length=11, verbose_name='联系电话')),
                ('birth', models.DateField(blank=True, null=True, verbose_name='生日')),
                ('qq', models.CharField(blank=True, default=0, max_length=15, verbose_name='QQ')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name_plural': '用户信息扩展',
                'verbose_name': '用户信息扩展',
            },
        ),
    ]
