# Generated by Django 2.0.2 on 2018-03-28 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0003_auto_20180328_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='quote_text',
            field=models.TextField(default='', verbose_name='引用评论内容'),
        ),
    ]
