# Generated by Django 2.0.2 on 2018-03-15 09:23

import ckeditor_uploader.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import read_statistics.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, verbose_name='文章标题')),
                ('detail', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='文章内容')),
                ('pub_date', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('pub_status', models.BooleanField(default=True, verbose_name='发布状态')),
                ('modify_date', models.DateTimeField(auto_now=True, verbose_name='最后修改时间')),
                ('comment_cout', models.IntegerField(default=0, verbose_name='评论数量')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='作者')),
            ],
            options={
                'verbose_name_plural': '文章',
                'verbose_name': '文章',
                'ordering': ('-pub_date',),
            },
            bases=(models.Model, read_statistics.models.ReadNumExtendMethod),
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='分类名称')),
                ('num', models.IntegerField(default=0, verbose_name='文章数量')),
            ],
            options={
                'verbose_name_plural': '文章分类',
                'verbose_name': '文章分类',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reply_info', models.CharField(default='', max_length=128, verbose_name='回复信息')),
                ('quote_info', models.TextField(default='', verbose_name='引用内容')),
                ('comment', models.TextField(verbose_name='评论内容')),
                ('cmt_date', models.DateTimeField(auto_now_add=True, verbose_name='评论时间')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Article', verbose_name='评论文章')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='评论用户')),
            ],
            options={
                'verbose_name_plural': '评论',
                'verbose_name': '评论',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Category', verbose_name='文章分类'),
        ),
    ]
