# Generated by Django 2.0.2 on 2018-03-15 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notice_title', models.CharField(max_length=128, verbose_name='公告标题')),
                ('notice_detail', models.TextField(verbose_name='公告内容')),
                ('notice_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('notice_status', models.BooleanField(default=True, verbose_name='发布状态')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('notice_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='接收人')),
            ],
            options={
                'verbose_name_plural': '系统通知',
                'verbose_name': '系统通知',
            },
        ),
        migrations.CreateModel(
            name='Sitemsg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_title', models.CharField(max_length=128, verbose_name='标题')),
                ('msg_detail', models.TextField(verbose_name='内容')),
                ('recv_user', models.CharField(max_length=128, verbose_name='接收人')),
                ('send_date', models.DateTimeField(auto_now_add=True, verbose_name='发送时间')),
                ('msg_status', models.BooleanField(default=False, verbose_name='已读')),
                ('is_delete', models.BooleanField(default=False, verbose_name='是否删除')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='发送人')),
            ],
            options={
                'verbose_name_plural': '站内信',
                'verbose_name': '站内信',
            },
        ),
    ]
